// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';
import { brokeredPreviewStorage } from './previewAuthStorage';

const IS_SERVER = typeof window === 'undefined';

function isNewSupabaseApiKey(value: string): boolean {
  return value.startsWith('sb_publishable_') || value.startsWith('sb_secret_');
}

function createSupabaseFetch(supabaseKey: string): typeof fetch {
  return (input, init) => {
    const headers = new Headers(
      typeof Request !== 'undefined' && input instanceof Request ? input.headers : undefined,
    );

    if (init?.headers) {
      new Headers(init.headers).forEach((value, key) => headers.set(key, value));
    }

    // New Supabase API keys are opaque strings, not bearer JWTs.
    if (isNewSupabaseApiKey(supabaseKey) && headers.get('Authorization') === `Bearer ${supabaseKey}`) {
      headers.delete('Authorization');
    }

    headers.set('apikey', supabaseKey);
    return fetch(input, { ...init, headers });
  };
}

function createSupabaseClient() {
  // Use import.meta.env for client-side (Vite build-time replacement).
  // Fall back to process.env for SSR (server-side rendering on Vercel/Nitro).
  // import.meta.env is replaced at build time by Vite (client bundle).
  // process.env is available at runtime on the Vercel/Nitro SSR server.
  const SUPABASE_URL: string =
    import.meta.env['VITE_SUPABASE_URL'] ||
    (typeof process !== 'undefined' ? (process.env['VITE_SUPABASE_URL'] ?? process.env['SUPABASE_URL'] ?? '') : '') ||
    '';

  const SUPABASE_PUBLISHABLE_KEY: string =
    import.meta.env['VITE_SUPABASE_PUBLISHABLE_KEY'] ||
    (typeof process !== 'undefined' ? (process.env['VITE_SUPABASE_PUBLISHABLE_KEY'] ?? process.env['SUPABASE_PUBLISHABLE_KEY'] ?? '') : '') ||
    '';

  if (!SUPABASE_URL || !SUPABASE_PUBLISHABLE_KEY) {
    console.warn(
      '[Supabase] VITE_SUPABASE_URL or VITE_SUPABASE_PUBLISHABLE_KEY is not set. ' +
      'The site will render without database features. ' +
      'Add these variables in Vercel → Settings → Environment Variables.',
    );
    // Return a no-op placeholder so the app never crashes — all queries simply
    // return empty data and the public pages render normally.
    return createClient<Database>('https://placeholder.supabase.co', 'placeholder-anon-key');
  }

  return createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
    global: {
      fetch: createSupabaseFetch(SUPABASE_PUBLISHABLE_KEY),
    },
    auth: {
      // brokeredPreviewStorage uses window/localStorage — only safe in the browser.
      // On the server (Vercel SSR) we pass undefined so Supabase skips auth storage.
      storage: IS_SERVER ? undefined : brokeredPreviewStorage(),
      persistSession: !IS_SERVER,
      autoRefreshToken: !IS_SERVER,
    },
  });
}

let _supabase: ReturnType<typeof createSupabaseClient> | undefined;

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";
export const supabase = new Proxy({} as ReturnType<typeof createSupabaseClient>, {
  get(_, prop, receiver) {
    if (!_supabase) _supabase = createSupabaseClient();
    return Reflect.get(_supabase, prop, receiver);
  },
});
